version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1si2c6dkecivo"
s3_prefix = "sam-app-hello-world"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
